version: '3'
services:
 web:
  build:
   context: ./
   dockerfile: web.docker
  container_name: familyphp
  volumes:
    - ./:/var/www/html
  ports:
   - "8002:80"
 db:
  build:
    context: ./
    dockerfile: db.docker
  container_name: familydbphp
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: example
  ports:
   - "33062:3306"
 composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./:/app
#docker-php-ext-install mysqli
#docker container exec -it my_mysql /bin/bash